const mmkal = require('eslint-plugin-mmkal')

module.exports = [
  ...mmkal.recommendedNextConfigs,
  {
    rules: {
      'no-console': 'off', // todo: reenable
      '@typescript-eslint/no-namespace': 'off', // mmkal
      'prefer-arrow-callback': 'off', // mmkal
      'unicorn/import-style': 'off', // mmkal
      // tanstack-router's `throw redirect(...)` is intentional control flow
      // — the throw is what unwinds the loader, not an Error. Same with the
      // tRPC -> Better Auth bridge throwing TRPCError-shaped objects.
      '@typescript-eslint/only-throw-error': 'off',
      // Unavoidable when interfacing with third-party `any`-returning APIs
      // (octokit, supabase, GitHub's webhook payloads). Better Auth's
      // additionalFields config types its profile loosely.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      // Pedantic; we only stringify primitives we know are strings/numbers.
      '@typescript-eslint/no-base-to-string': 'off',
      // Inner-scope same-name `c` for "client" / `githubLogin` for the
      // refined value is intentional and readable.
      '@typescript-eslint/no-shadow': 'off',
      // Our small CLI scripts (sync-github-app-webhook.ts,
      // dangerdanger-recreate-production.cjs) are exactly the case
      // process.exit/promise-chain rules say to avoid in libraries.
      'unicorn/no-process-exit': 'off',
      'unicorn/prefer-top-level-await': 'off',
      // Cosmetic; not changing string literals like 'utf-8' → 'utf8'.
      'unicorn/text-encoding-identifier-case': 'off',
      'unicorn/prefer-code-point': 'off',
    },
  },
  {
    ignores: [
      '**/generated/**',
      '**/dist/**',
      '**/.alchemy/**',
      '**/.astro/**',
      '**/.wrangler/**',
      '**/.vercel/**',
      'bundled-action/**',
      // Generated by `tanstack/start` at build time.
      'apps/app/src/routeTree.gen.ts',
    ],
  },
]
