// Generated by `sqlfu generate`. Do not edit.
// A bundle of every migration in migrations/,
// importable from runtimes without filesystem access (durable objects, edge workers, browsers).
// Use `migrate(client)` for the common path, or `migrations` for lower-level control.

import {applyMigrations, migrationsFromBundle, type AsyncClient, type Client, type SyncClient} from 'sqlfu';

export const migrations = {
};

export function migrate(client: SyncClient): void;
export function migrate(client: AsyncClient): Promise<void>;
export function migrate(client: Client): void | Promise<void> {
  return applyMigrations(client, {
    migrations: migrationsFromBundle(migrations),
    preset: "d1",
  });
}

export type MigrationBundle = typeof migrations;
