/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactViewRouteImport } from './routes/artifact.view'
import { Route as ArtifactViewOwnerRouteImport } from './routes/artifact.view_.$owner'
import { Route as ArtifactViewOwnerRepoRouteImport } from './routes/artifact.view_.$owner_.$repo'
import { Route as ArtifactViewOwnerRepoAliasTypeRouteImport } from './routes/artifact.view_.$owner_.$repo_.$aliasType'
import { Route as ArtifactViewOwnerRepoAliasTypeIdentifierRouteImport } from './routes/artifact.view_.$owner_.$repo_.$aliasType_.$identifier'
import { Route as ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRouteImport } from './routes/artifact.view_.$owner_.$repo_.$aliasType_.$identifier_.$artifactName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactViewRoute = ArtifactViewRouteImport.update({
  id: '/artifact/view',
  path: '/artifact/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactViewOwnerRoute = ArtifactViewOwnerRouteImport.update({
  id: '/artifact/view_/$owner',
  path: '/artifact/view/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactViewOwnerRepoRoute = ArtifactViewOwnerRepoRouteImport.update({
  id: '/artifact/view_/$owner_/$repo',
  path: '/artifact/view/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactViewOwnerRepoAliasTypeRoute =
  ArtifactViewOwnerRepoAliasTypeRouteImport.update({
    id: '/artifact/view_/$owner_/$repo_/$aliasType',
    path: '/artifact/view/$owner/$repo/$aliasType',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArtifactViewOwnerRepoAliasTypeIdentifierRoute =
  ArtifactViewOwnerRepoAliasTypeIdentifierRouteImport.update({
    id: '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier',
    path: '/artifact/view/$owner/$repo/$aliasType/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute =
  ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRouteImport.update({
    id: '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier_/$artifactName',
    path: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/artifact/view': typeof ArtifactViewRoute
  '/artifact/view/$owner': typeof ArtifactViewOwnerRoute
  '/artifact/view/$owner/$repo': typeof ArtifactViewOwnerRepoRoute
  '/artifact/view/$owner/$repo/$aliasType': typeof ArtifactViewOwnerRepoAliasTypeRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier': typeof ArtifactViewOwnerRepoAliasTypeIdentifierRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName': typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/artifact/view': typeof ArtifactViewRoute
  '/artifact/view/$owner': typeof ArtifactViewOwnerRoute
  '/artifact/view/$owner/$repo': typeof ArtifactViewOwnerRepoRoute
  '/artifact/view/$owner/$repo/$aliasType': typeof ArtifactViewOwnerRepoAliasTypeRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier': typeof ArtifactViewOwnerRepoAliasTypeIdentifierRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName': typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/artifact/view': typeof ArtifactViewRoute
  '/artifact/view_/$owner': typeof ArtifactViewOwnerRoute
  '/artifact/view_/$owner_/$repo': typeof ArtifactViewOwnerRepoRoute
  '/artifact/view_/$owner_/$repo_/$aliasType': typeof ArtifactViewOwnerRepoAliasTypeRoute
  '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier': typeof ArtifactViewOwnerRepoAliasTypeIdentifierRoute
  '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier_/$artifactName': typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/artifact/view'
    | '/artifact/view/$owner'
    | '/artifact/view/$owner/$repo'
    | '/artifact/view/$owner/$repo/$aliasType'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/artifact/view'
    | '/artifact/view/$owner'
    | '/artifact/view/$owner/$repo'
    | '/artifact/view/$owner/$repo/$aliasType'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/artifact/view'
    | '/artifact/view_/$owner'
    | '/artifact/view_/$owner_/$repo'
    | '/artifact/view_/$owner_/$repo_/$aliasType'
    | '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier'
    | '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier_/$artifactName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  ArtifactViewRoute: typeof ArtifactViewRoute
  ArtifactViewOwnerRoute: typeof ArtifactViewOwnerRoute
  ArtifactViewOwnerRepoRoute: typeof ArtifactViewOwnerRepoRoute
  ArtifactViewOwnerRepoAliasTypeRoute: typeof ArtifactViewOwnerRepoAliasTypeRoute
  ArtifactViewOwnerRepoAliasTypeIdentifierRoute: typeof ArtifactViewOwnerRepoAliasTypeIdentifierRoute
  ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute: typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view': {
      id: '/artifact/view'
      path: '/artifact/view'
      fullPath: '/artifact/view'
      preLoaderRoute: typeof ArtifactViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view_/$owner': {
      id: '/artifact/view_/$owner'
      path: '/artifact/view/$owner'
      fullPath: '/artifact/view/$owner'
      preLoaderRoute: typeof ArtifactViewOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view_/$owner_/$repo': {
      id: '/artifact/view_/$owner_/$repo'
      path: '/artifact/view/$owner/$repo'
      fullPath: '/artifact/view/$owner/$repo'
      preLoaderRoute: typeof ArtifactViewOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view_/$owner_/$repo_/$aliasType': {
      id: '/artifact/view_/$owner_/$repo_/$aliasType'
      path: '/artifact/view/$owner/$repo/$aliasType'
      fullPath: '/artifact/view/$owner/$repo/$aliasType'
      preLoaderRoute: typeof ArtifactViewOwnerRepoAliasTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier': {
      id: '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier'
      path: '/artifact/view/$owner/$repo/$aliasType/$identifier'
      fullPath: '/artifact/view/$owner/$repo/$aliasType/$identifier'
      preLoaderRoute: typeof ArtifactViewOwnerRepoAliasTypeIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier_/$artifactName': {
      id: '/artifact/view_/$owner_/$repo_/$aliasType_/$identifier_/$artifactName'
      path: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
      fullPath: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
      preLoaderRoute: typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  ArtifactViewRoute: ArtifactViewRoute,
  ArtifactViewOwnerRoute: ArtifactViewOwnerRoute,
  ArtifactViewOwnerRepoRoute: ArtifactViewOwnerRepoRoute,
  ArtifactViewOwnerRepoAliasTypeRoute: ArtifactViewOwnerRepoAliasTypeRoute,
  ArtifactViewOwnerRepoAliasTypeIdentifierRoute:
    ArtifactViewOwnerRepoAliasTypeIdentifierRoute,
  ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute:
    ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
