/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRouteImport } from './routes/artifact.view.$owner.$repo.$aliasType.$identifier.$artifactName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute =
  ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRouteImport.update({
    id: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName',
    path: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName': typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName': typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName': typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute: typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName': {
      id: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
      path: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
      fullPath: '/artifact/view/$owner/$repo/$aliasType/$identifier/$artifactName'
      preLoaderRoute: typeof ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute:
    ArtifactViewOwnerRepoAliasTypeIdentifierArtifactNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
