import {type PathParams} from './params'
import {auth, getCollaborationLevel, getInstallationOctokit} from '~/auth'
import {client, sql} from '~/db'

export const searchArtifacts = async (params: Partial<PathParams>, {offset = 0, limit = 100} = {}) => {
  const session = await auth()
  if (!session?.user.github_login) return []
  const owner = params.owner || session?.user.github_login

  const artifacts = await client.any(sql<queries.Artifact>`
    select
      a.id artifact_id,
      a.name,
      ai.type alias_type,
      ai.value identifier,
      repos.owner, repos.name repo, ins.github_id as installation_github_id
    from artifacts a
    join artifact_identifiers ai on ai.artifact_id = a.id
    join repos on repos.id = a.repo_id
    join github_installations ins on ins.id = a.installation_id
    where
      owner = ${owner}
      and repos.name = ${params.repo || sql`repos.name`}
      and ai.type = ${params.aliasType || sql`ai.type`}
      and ai.value = ${params.identifier || sql`ai.value`}
      and a.name = ${params.artifactName || sql`a.name`}
    order by a.created_at desc, ai.type, a.name
    limit ${limit} offset ${offset}
  `)
  if (!artifacts.length) return []

  const octokit = await getInstallationOctokit(artifacts[0].installation_github_id)

  const dedupedRepos = Object.values(Object.fromEntries(artifacts.map(r => [`${r.owner}/${r.repo}`, r])))
  for (const repo of dedupedRepos) {
    const permission = await getCollaborationLevel(octokit, repo, session.user.github_login)
    if (permission === 'none') return []
  }

  return artifacts.map(a => {
    const pathParams: PathParams = {
      owner: a.owner,
      repo: a.repo,
      aliasType: a.alias_type,
      identifier: a.identifier,
      artifactName: a.name,
    }
    return {
      artifactId: a.artifact_id,
      pathParams,
      installationId: a.installation_github_id,
    }
  })
}

export declare namespace queries {
  // Generated by @pgkit/typegen

  /** - query: `select a.id artifact_id, a.name, ai.type... [truncated] ...desc, ai.type, a.name limit $6 offset $7` */
  export interface Artifact {
    /** column: `public.artifacts.id`, not null: `true`, regtype: `prefixed_ksuid` */
    artifact_id: import('~/db').Id<'artifacts'>

    /** column: `public.artifacts.name`, not null: `true`, regtype: `text` */
    name: string

    /** column: `public.artifact_identifiers.type`, not null: `true`, regtype: `text` */
    alias_type: string

    /** column: `public.artifact_identifiers.value`, not null: `true`, regtype: `text` */
    identifier: string

    /** column: `public.repos.owner`, not null: `true`, regtype: `text` */
    owner: string

    /** column: `public.repos.name`, not null: `true`, regtype: `text` */
    repo: string

    /** column: `public.github_installations.github_id`, not null: `true`, regtype: `bigint` */
    installation_github_id: number
  }
}
