// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type AccountRow = {
	id: string;
	accountId: string;
	providerId: string;
	userId: string;
	accessToken: string | null;
	refreshToken: string | null;
	idToken: string | null;
	accessTokenExpiresAt: string | null;
	refreshTokenExpiresAt: string | null;
	scope: string | null;
	password: string | null;
	createdAt: string;
	updatedAt: string;
};

export type ArtifactEntriesRow = {
	id: string;
	artifact_id: string;
	entry_name: string;
	aliases: string;
	storage_pathname: string;
	created_at: string;
	updated_at: string;
};

export type ArtifactIdentifiersRow = {
	id: string;
	artifact_id: string;
	type: string;
	value: string;
	created_at: string;
	updated_at: string;
};

export type ArtifactsRow = {
	id: string;
	repo_id: string;
	name: string;
	github_id: number;
	download_url: string | null;
	installation_id: string;
	visibility: string;
	created_at: string;
	updated_at: string;
};

export type GithubInstallationsRow = {
	id: string;
	github_id: number;
	removed_at: string | null;
	created_at: string;
	updated_at: string;
};

export type ReposRow = {
	id: string;
	owner: string;
	name: string;
	installation_id: string;
	default_visibility: string;
	created_at: string;
	updated_at: string;
};

export type SessionRow = {
	id: string;
	expiresAt: string;
	token: string;
	createdAt: string;
	updatedAt: string;
	ipAddress: string | null;
	userAgent: string | null;
	userId: string;
	impersonatedBy: string | null;
};

export type SponsorsRow = {
	id: string;
	sponsor_login: string;
	sponsoree_login: string;
	github_type: string;
	monthly_amount_usd: number | null;
	expiry: string;
	created_at: string;
	updated_at: string;
};

export type UploadTokensRow = {
	token_hash: string;
	github_login: string;
	created_at: number;
	expires_at: number;
};

export type UsageCreditsRow = {
	id: string;
	github_login: string;
	expiry: string;
	sponsor_id: string | null;
	reason: string;
	created_at: string;
	updated_at: string;
};

export type UserRow = {
	id: string;
	name: string;
	email: string;
	emailVerified: number;
	image: string | null;
	createdAt: string;
	updatedAt: string;
	role: string | null;
	banned: number | null;
	banReason: string | null;
	banExpires: string | null;
	githubLogin: string | null;
};

export type VerificationRow = {
	id: string;
	identifier: string;
	value: string;
	expiresAt: string;
	createdAt: string;
	updatedAt: string;
};
