import {NextRequest, NextResponse} from 'next/server'
import {client, sql} from '../../../db'

/** Responds with public info about the signed-in user and logs the full auth object */
export async function GET(_request: NextRequest) {
  const testTableData = await client.one(sql<queries.TestTable>`
    insert into test_table (id, name) values (1, 'one')
    on conflict (id) do update set name = excluded.name
    returning *
  `)
  return NextResponse.json({
    testTableData,
  })
}

export declare namespace queries {
  // Generated by @pgkit/typegen

  /** - query: `insert into test_table (id, name) values (1, 'one') on conflict (id) do update set name = 'one' returning *` */
  export interface TestTable {
    /** column: `public.test_table.id`, not null: `true`, regtype: `integer` */
    id: number

    /** column: `public.test_table.name`, not null: `true`, regtype: `text` */
    name: string
  }
}
