import esbuild from 'esbuild'
import {mkdir, rm, writeFile} from 'node:fs/promises'
import {builtinModules} from 'node:module'
import path from 'node:path'

const builtinModuleNames = new Set(builtinModules.concat(builtinModules.map(name => `node:${name}`)))
const vendorExports = {
  '@actions/artifact': {named: ['DefaultArtifactClient']},
  '@actions/core': {named: ['getInput', 'isDebug', 'setFailed', 'setOutput']},
  '@actions/github': {named: ['context', 'getOctokit']},
  '@actions/glob': {named: ['create', 'hashFiles']},
  '@actions/http-client': {named: ['HttpClient']},
  '@trpc/client': {named: ['createTRPCClient', 'httpLink']},
  'badge-maker': {named: ['ValidationError', 'makeBadge']},
  'p-suite/p-map': {default: true, named: []},
  unzipit: {named: ['unzip']},
  zod: {named: ['z']},
}

const actions = {
  badge: {
    entryPoint: 'src/action/badge.ts',
    outfile: 'bundled-action/badge.js',
  },
  upload: {
    entryPoint: 'src/action/upload.ts',
    outfile: 'bundled-action/upload.js',
  },
}

async function main() {
  const thirdPartyModules = new Set()
  const firstPartyOutputs = await Promise.all(
    Object.entries(actions).map(async ([actionName, action]) => ({
      actionName,
      action,
      result: await buildFirstPartyAction(action.entryPoint, thirdPartyModules),
    })),
  )

  await rm('bundled-action', {recursive: true, force: true})
  await mkdir('bundled-action', {recursive: true})

  await buildVendorChunks(Array.from(thirdPartyModules).sort())

  await Promise.all(
    firstPartyOutputs.map(({actionName, action, result}) =>
      writeFile(action.outfile, actionSource({actionName, firstPartySource: text(result)})),
    ),
  )
}

async function buildFirstPartyAction(entryPoint, thirdPartyModules) {
  return esbuild.build({
    absWorkingDir: process.cwd(),
    bundle: true,
    entryPoints: [entryPoint],
    format: 'esm',
    legalComments: 'none',
    logLevel: 'silent',
    minify: false,
    platform: 'node',
    plugins: [externalizeThirdPartyDependencies(thirdPartyModules)],
    target: 'node20',
    write: false,
  })
}

async function buildVendorChunks(moduleNames) {
  const tempDir = 'tmp/artifact-action-vendor-ignoreme'
  await rm(tempDir, {recursive: true, force: true})
  await mkdir(tempDir, {recursive: true})

  const entryPoints = {}
  await Promise.all(
    moduleNames.map(async moduleName => {
      const stem = vendorFileStem(moduleName)
      const entryPoint = path.join(tempDir, `${stem}.js`)
      entryPoints[stem] = entryPoint
      await writeFile(entryPoint, vendorEntrySource(moduleName))
    }),
  )

  await esbuild.build({
    absWorkingDir: process.cwd(),
    banner: {js: 'import {createRequire} from "node:module";const require=createRequire(import.meta.url);'},
    bundle: true,
    chunkNames: 'chunks/[name]-[hash]',
    entryNames: '[name]',
    entryPoints,
    format: 'esm',
    legalComments: 'none',
    logLevel: 'silent',
    minify: true,
    outdir: 'bundled-action/vendor',
    platform: 'node',
    splitting: true,
    target: 'node20',
  })

  await rm(tempDir, {recursive: true, force: true})
}

function externalizeThirdPartyDependencies(thirdPartyModules) {
  return {
    name: 'externalize-third-party-dependencies',
    setup(build) {
      build.onResolve({filter: /.*/}, args => {
        if (!isThirdPartyDependency(args.path)) return
        thirdPartyModules.add(args.path)
        return {external: true, path: `./vendor/${vendorFileStem(args.path)}.js`}
      })
    },
  }
}

function isThirdPartyDependency(specifier) {
  if (specifier.startsWith('.') || specifier.startsWith('/') || specifier.startsWith('#')) return false
  if (specifier.startsWith('@artifact/')) return false
  if (builtinModuleNames.has(specifier)) return false
  return true
}

function vendorEntrySource(moduleName) {
  const exports = vendorExports[moduleName]
  if (!exports) throw new Error(`missing explicit vendor export map for ${moduleName}`)

  const source = [`import * as mod from ${JSON.stringify(moduleName)}`]
  exports.named.forEach(name => {
    source.push(`export const ${name} = mod.${name}`)
  })
  if (exports.default) source.push('export default mod.default || mod')
  return source.join('\n')
}

function vendorFileStem(moduleName) {
  return moduleName.replace(/^@/, '').replaceAll(/[^\dA-Za-z]+/g, '-')
}

function actionSource({actionName, firstPartySource}) {
  return [
    `// Generated by scripts/build-action.js for the ${actionName} action.`,
    '// Repository-owned action code is intentionally kept readable; third-party dependencies are bundled in ./vendor.',
    firstPartySource,
    '',
  ].join('\n')
}

function text(result) {
  const output = result.outputFiles[0]
  if (!output) throw new Error('expected esbuild to return one output file')
  return output.text.trimEnd()
}

main().catch(error => {
  console.error(error)
  process.exitCode = 1
})
