import {buildArtifactFileResponse} from '@artifact/domain/artifact/build-file-response'
import {type PathParams} from '@artifact/domain/artifact/path-params'
import {resolveArtifactRequest} from '@artifact/domain/artifact/resolve-artifact-request'
import {checkCanAccess, getInstallationOctokit} from '~/auth'
import {client, sql} from '~/db'
import {supabaseStorageServiceRoleClient} from '~/storage/supabase'
import {logger} from '~/tag-logger'

export const loadArtifact = async (login: string | null | undefined, {params}: {params: PathParams}) => {
  logger.tag('params').debug(params)
  const result = await resolveArtifactRequest(login, params, {
    async findArtifactInfo({owner, repo, aliasType, identifier, artifactName}) {
      const artifactInfo = await client.maybeOne(sql<queries.ArtifactInfo>`
        select
          i.github_id as installation_github_id,
          a.id as artifact_id,
          a.visibility,
          (select array_agg(entry_name) from artifact_entries ae where ae.artifact_id = a.id) entries
        from artifacts a
        join artifact_identifiers aid on aid.artifact_id = a.id
        join github_installations i on i.id = a.installation_id
        join repos r on r.id = a.repo_id
        where a.name = ${artifactName}
        and aid.type = ${aliasType}
        and aid.value = ${identifier}
        and r.owner = ${owner}
        and r.name = ${repo}
        order by a.created_at desc
        limit 1
      `)

      if (!artifactInfo) return null

      return {
        installationGithubId: artifactInfo.installation_github_id,
        artifactId: artifactInfo.artifact_id,
        visibility: artifactInfo.visibility,
        entries: artifactInfo.entries,
      }
    },
    async checkAccess({installationGithubId, artifactId, owner, repo, githubLogin}) {
      const octokit = await getInstallationOctokit(installationGithubId)
      return checkCanAccess(octokit, {
        owner,
        repo,
        username: githubLogin,
        artifactId,
      })
    },
    async findStoragePathname({artifactId, entry}) {
      const dbFile = await client.maybeOne(sql<queries.DbFile>`
        select o.name as storage_pathname
        from artifacts a
        join artifact_entries ae on ae.artifact_id = a.id
        join storage.objects o on ae.storage_object_id = o.id
        where a.id = ${artifactId}
        and ${entry} = any(ae.aliases)
        and o.name is not null
        order by ae.created_at desc
        limit 1
      `)

      return dbFile?.storage_pathname || null
    },
  })

  if (result.code === 'artifact_not_found' || result.code === 'not_authorized') {
    return result
  }

  return {
    ...result,
    artifactInfo: {
      installation_github_id: result.artifactInfo.installationGithubId,
      artifact_id: result.artifactInfo.artifactId,
      visibility: result.artifactInfo.visibility,
      entries: result.artifactInfo.entries,
    },
    loaderParams: {
      ...result.loaderParams,
      githubLogin: result.loaderParams.githubLogin,
    },
  }
}

export async function loadFile(storagePathname: string, params: PathParams, options?: {raw?: boolean}) {
  const storage = supabaseStorageServiceRoleClient()
  return buildArtifactFileResponse(
    storagePathname,
    params,
    {
      async getObjectResponse(pathname) {
        const file = await storage.object.bucketName('artifact_files').wildcard(pathname).get()
        return file.response
      },
    },
    options,
  )
}

export declare namespace queries {
  // Generated by @pgkit/typegen

  /** - query: `select i.github_id as installation_githu... [truncated] ... = $5 order by a.created_at desc limit 1` */
  export interface ArtifactInfo {
    /** column: `public.github_installations.github_id`, not null: `true`, regtype: `bigint` */
    installation_github_id: number

    /** column: `public.artifacts.id`, not null: `true`, regtype: `prefixed_ksuid` */
    artifact_id: import('~/db').Id<'artifacts'>

    /** column: `public.artifacts.visibility`, not null: `true`, regtype: `text` */
    visibility: string

    /**
     * From CTE subquery "subquery_3_for_column_entries"
     *
     * column: `✨.subquery_3_for_column_entries.entries`, regtype: `text[]`
     */
    entries: string[] | null
  }

  /** - query: `select o.name as storage_pathname from a... [truncated] ...null order by ae.created_at desc limit 1` */
  export interface DbFile {
    /** column: `storage.objects.name`, regtype: `text` */
    storage_pathname: string | null
  }
}
